permalink: /:categories:month/:title
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
url: http://emrengin.github.com
exclude:
        - Rakefile
        - Makefile
        - presentation.md
        - presentation.html
        - presentation.png
        - media

account: emrengin
archive: Son Girdiler
assets: /assets
author: Emre Engin
disqus: ~
email: emre.engin@bil.omu.edu.tr
facebook: ~
feed: ~
flickr: ~
google: ~
googleanalyticsid: UA-36074174-1
googleplus: ~
gpg: ~
homeurl: http://emrengin.github.com
logo: /assets/19/19-normal-128x128.png
organization: ~
picasa: ~
related: Diğer Girdiler
repository: emrengin.github.com
ribbon: GitHub'dayım
title: Emre Engin
twitter: ~

navigator:
        0: Teknik Olmayan Yazılar
        1: Teknik Yazılar
        9: Kısa Notlar
